
package View;

import Controller.CandidatoController;
import Controller.VotosController;
import Model.Candidato;
import Model.Votos;
import java.util.ArrayList;


public class Urna extends javax.swing.JFrame {
VotosController VotosController;
CandidatoController CandidatosController;
    /**
     * Creates new form telaVotacao
     */
    public Urna() {
        initComponents();
    VotosController = new VotosController();
    CandidatosController = new CandidatoController();
    }
    String receber = "";
    String npt="";
    String receber1 = "";
    String vto="";
    String nulo="";
    public static void mostrarListagem() {
        VotosListagem c = new VotosListagem();
        c.setTitle("Listagem");
        c.setLocationRelativeTo(null);
        c.setVisible(true);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao1 = new javax.swing.JButton();
        btBranco = new javax.swing.JButton();
        botao3 = new javax.swing.JButton();
        botao5 = new javax.swing.JButton();
        botao4 = new javax.swing.JButton();
        botao8 = new javax.swing.JButton();
        botao7 = new javax.swing.JButton();
        botao9 = new javax.swing.JButton();
        botao0 = new javax.swing.JButton();
        candidato = new javax.swing.JLabel();
        botao2 = new javax.swing.JButton();
        botao6 = new javax.swing.JButton();
        botaoConfirme = new javax.swing.JButton();
        botaoCorrige = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botao1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botao1.setText("1");
        botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao1ActionPerformed(evt);
            }
        });

        btBranco.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        btBranco.setText("BRANCO");
        btBranco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBrancoActionPerformed(evt);
            }
        });

        botao3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botao3.setText("3");
        botao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao3ActionPerformed(evt);
            }
        });

        botao5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botao5.setText("5");
        botao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao5ActionPerformed(evt);
            }
        });

        botao4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botao4.setText("4");
        botao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao4ActionPerformed(evt);
            }
        });

        botao8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botao8.setText("8");
        botao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao8ActionPerformed(evt);
            }
        });

        botao7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botao7.setText("7");
        botao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao7ActionPerformed(evt);
            }
        });

        botao9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botao9.setText("9");
        botao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao9ActionPerformed(evt);
            }
        });

        botao0.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botao0.setText("0");
        botao0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao0ActionPerformed(evt);
            }
        });

        candidato.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        candidato.setText("Candidato");

        botao2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botao2.setText("2");
        botao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao2ActionPerformed(evt);
            }
        });

        botao6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botao6.setText("6");
        botao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao6ActionPerformed(evt);
            }
        });

        botaoConfirme.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        botaoConfirme.setText("CONFIRME");
        botaoConfirme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmeActionPerformed(evt);
            }
        });

        botaoCorrige.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        botaoCorrige.setText("CORRIGE");
        botaoCorrige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCorrigeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(candidato, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(botao1)
                        .addGap(4, 4, 4)
                        .addComponent(botao2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(botao4)
                        .addGap(5, 5, 5)
                        .addComponent(botao5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(botao7)
                        .addGap(5, 5, 5)
                        .addComponent(botao8)
                        .addGap(5, 5, 5)
                        .addComponent(botao9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(botao0))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(botaoCorrige)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoConfirme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBranco)))
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(candidato, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botao1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botao3)
                        .addComponent(botao2)))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botao4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botao5)
                        .addComponent(botao6)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botao7)
                    .addComponent(botao8)
                    .addComponent(botao9))
                .addGap(13, 13, 13)
                .addComponent(botao0, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBranco)
                    .addComponent(botaoConfirme)
                    .addComponent(botaoCorrige)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao5ActionPerformed
        if (receber.equals("")) {
            receber = "5";
            candidato.setText(receber);
        } else if (receber1.equals("")) {
            receber1 = "5";
            candidato.setText(receber + receber1);
        }

    }//GEN-LAST:event_botao5ActionPerformed

    private void botao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao8ActionPerformed
        if (receber.equals("")) {
            receber = "8";
            candidato.setText(receber);
        } else if (receber1.equals("")) {
            receber1 = "8";
            candidato.setText(receber + receber1);
        }

    }//GEN-LAST:event_botao8ActionPerformed

    private void botao0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao0ActionPerformed
        if (receber.equals("")) {
            receber = "0";
            candidato.setText(receber);
        } else if (receber1.equals("")) {
            receber1 = "0";
            candidato.setText(receber + receber1);
        }

    }//GEN-LAST:event_botao0ActionPerformed

    private void botao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao7ActionPerformed
        if (receber.equals("")) {
            receber = "7";
            candidato.setText(receber); 
        } else if (receber1.equals("")) {
            receber1 = "7";
            candidato.setText(receber + receber1);
        }

    }//GEN-LAST:event_botao7ActionPerformed

    private void botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao1ActionPerformed
        if (receber.equals("")) {
            receber = "1";
            candidato.setText(receber);
        } else if (receber1.equals("")) {
            receber1 = "1";
            candidato.setText(receber + receber1);
        }

    }//GEN-LAST:event_botao1ActionPerformed

        
    private void botao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao4ActionPerformed
        if (receber.equals("")) {
          receber = "4";  
          candidato.setText(receber);
        } else if (receber1.equals("")) {
            receber1 = "4";
            candidato.setText(receber + receber1);
        }
     }//GEN-LAST:event_botao4ActionPerformed

    private void btBrancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBrancoActionPerformed
   vto="VOTOBRANCO";
    }//GEN-LAST:event_btBrancoActionPerformed

    private void botao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao3ActionPerformed
        if (receber.equals("")) {
            receber = "3";
            candidato.setText(receber);
        } else if (receber1.equals("")) {
            receber1 = "3";
            candidato.setText(receber + receber1);
        }
    }//GEN-LAST:event_botao3ActionPerformed

    private void botao9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao9ActionPerformed
        if (receber.equals("")) {

            receber = "9";
            candidato.setText(receber);
        } else if (receber1.equals("")) {
            receber1 = "9";
            candidato.setText(receber + receber1);
        }
    }//GEN-LAST:event_botao9ActionPerformed

    private void botao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao2ActionPerformed
if (receber.equals("")) {
            receber = "2";
            candidato.setText(receber);
        } else if (receber1.equals("")) {
            receber1 = "2";
            candidato.setText(receber + receber1);
        }       
    }//GEN-LAST:event_botao2ActionPerformed

    private void botao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao6ActionPerformed
        if (receber.equals("")) {

            receber = "6";
            candidato.setText(receber);
        } else if (receber1.equals("")) {
            receber1 = "6";
            candidato.setText(receber + receber1);
        }
    }//GEN-LAST:event_botao6ActionPerformed

    private void botaoConfirmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmeActionPerformed
        
        npt="";
        String rpt= "";  
   ArrayList<Candidato> listaCandidato = CandidatosController.buscarCandidato();
   ArrayList<Votos> listaVotos = VotosController.buscarVotos();
         if(! candidato.getText().equals("Candidato")){
         npt=candidato.getText();
        Integer ncdt = Integer.parseInt(npt);
        if (ncdt!= null){
        for (Candidato c : listaCandidato) {
            if(ncdt==c.getNumero()){
                VotosController.CapturarVotos(ncdt);
                mostrarListagem();
                this.setVisible(false);
                ;
               break;
            }
            }
        }
   }
         if (vto.equals("VOTOBRANCO")){ 
                mostrarListagem();
                this.setVisible(false);
         }
               
    }//GEN-LAST:event_botaoConfirmeActionPerformed

    private void botaoCorrigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCorrigeActionPerformed
       candidato.setText("Candidato");
        receber = "";
        botaoConfirme.setVisible(true);
        receber1 = "";
        vto="";
    }//GEN-LAST:event_botaoCorrigeActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Urna().setVisible(true);
            }
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao0;
    private javax.swing.JButton botao1;
    private javax.swing.JButton botao2;
    private javax.swing.JButton botao3;
    private javax.swing.JButton botao4;
    private javax.swing.JButton botao5;
    private javax.swing.JButton botao6;
    private javax.swing.JButton botao7;
    private javax.swing.JButton botao8;
    private javax.swing.JButton botao9;
    private javax.swing.JButton botaoConfirme;
    private javax.swing.JButton botaoCorrige;
    private javax.swing.JButton btBranco;
    private javax.swing.JLabel candidato;
    // End of variables declaration//GEN-END:variables
}
